blank_issues_enabled: false
contact_links:
  - name: Feature & Change Request
    url: https://github.com/jensrossbach/esphome-luxtronik-v1/discussions/categories/ideas-requests
    about: Suggest an idea or request a change for this project
  - name: Discussion Forum
    url: https://github.com/jensrossbach/esphome-luxtronik-v1/discussions
    about: Ask questions, get help and provide feedback
